name: Push To Production

on:
  push:
    branches: [ main ]

jobs:
  build-production:
    container: node:16
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup up git user
        run: |
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'
          git fetch --all
      - name: Build
        run: |
          npm ci
          npm run build
      - name: Publish
        run: |
          git add docs --force
          git commit -m 'Committed build: ${{ github.sha }}'
          git push -f gh-pages
