name: Deploy Jour

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Jour
        run: |
          npm ci
          npm run build
      - name: Deploy Jour
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          user_name: '${{ github.actor }}'
          user_email: '${{ github.actor }}@users.noreply.github.com'
